version: "2"
services:
    rails:
        build: .
        volumes:
            - './:/app'
        ports:
            - "3000:3000"
        env_file: .env
    #####################
    # Postgres
    #####################
    #####################
    # MySQL
    #####################
    #####################
    # Mongo
    #####################
    #####################
    # Redis
    #####################
    #####################
    # Memcached
    #####################
    #####################
    # NGINX
    #####################
