version: "2"
services:

### Ruby on Rails #########################
    rails:
        build: .
        volumes:
            - './:/app'
        ports:
            - "3000:3000"
        links:
            - postgres
            - redis 
        env_file: .env

### PostgreSQL #############################

    postgres:
        image: postgres:latest
        volumes: # Remove the comments to persist data
            - /var/lib/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres

### MySQL ###################################

    mysql:
        image: mysql:latest
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            # - MYSQL_ALLOW_EMPTY_PASSWORD=
            # - MYSQL_RANDOM_ROOT_PASSWORD=
            # - MYSQL_ONETIME_PASSWORD=
            # - MYSQL_DATABASE= # Specify a default database to be created

### MongoDB #################################

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - /var/lib/mongo:/data/db

### Redis ###################################

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - /var/lib/redis:/data
